#!/bin/bash -e

NAME=buildbotics
ETC=/etc/$NAME
RUN=/var/run/$NAME
LOG=/var/log/$NAME

case "$1" in
    reconfigure|configure)
        # Setup permissions
        chown -R $NAME:root $ETC $RUN $LOG
        chmod 755 $ETC $RUN $LOG

        # Start the service
        ln -sf /usr/share/$NAME/$NAME.service /etc/systemd/system/
        if [ -e $ETC/config.xml ]; then
            service $NAME start || true
        fi
        ;;
esac
