#!/bin/bash -e

NAME=buildbotics

case "$1" in
    remove)
        # Stop the service
        service $NAME stop || true
        ;;

    purge)
        # Remove files
        rm -rf /etc/$NAME /etc/default/$NAME /var/lib/$NAME
        rm -f /etc/systemd/system/$NAME.service

        # Remove user if it exists
        if getent passwd $NAME >/dev/null; then
            echo -n "Removing system user $NAME..."
            if userdel $NAME 2>/dev/null; then
                echo "done"
            else
                echo "failed"
            fi
        fi

        # Remove group if it exists
        if getent group $NAME >/dev/null; then
            echo -n "Removing system group $NAME..."
            if groupdel $NAME 2>/dev/null; then
                echo "done"
            else
                echo "failed"
            fi
        fi
        ;;
esac
