#!/bin/bash -e

NAME=buildbotics
ETC=/etc/$NAME
RUN=/var/run/$NAME
LOG=/var/log/$NAME

case "$1" in
    install|upgrade)
        if [ "$1" == "upgrade" ]; then
            # Stop the service
            if [ -x insserv ]; then
                service $NAME stop || true
            else
                invoke-rc.d $NAME stop || true
            fi
        fi

        # Create directories
        test -d $ETC || mkdir $ETC
        test -d $RUN || mkdir $RUN
        test -d $LOG || mkdir $LOG

        # Create group if it does not exist
        if ! getent group $NAME >/dev/null; then
            echo -n "Adding system group $NAME..."
            if groupadd -r $NAME 2>/dev/null; then
                echo "done"
            else
                echo "failed"
            fi
        fi

        # Create user if it does not exist
        if ! getent passwd $NAME >/dev/null; then
            echo -n "Adding system user $NAME..."
            if useradd -r -g $NAME $NAME 2>/dev/null; then
                echo "done"
            else
                echo "failed"
            fi
        fi
        ;;
esac
